version: '3'
services: 
  database:
    restart: always
    build: database
    ports:
      - "5432:5432"
    volumes:
      - database/volume:/var/lib/postgresq/data
  scraper:
    restart: always
    build: delta_scraper
    ports:
      - "8000:8000"
  website:
    restart: always
    build: www


