DROP TABLE IF EXISTS DOCUMENTS;
DROP TABLE IF EXISTS POSTS;
DROP TABLE IF EXISTS VISITOR;
DROP TABLE IF EXISTS COMMENTS;

-- To generate unique ID's for posts
CREATE EXTENSION "uuid-ossp";

-- Can make some funnier random name generation
CREATE FUNCTION DEFAULT_NAME() RETURNS VARCHAR(255) AS $$
    SELECT 'smith';
$$ LANGUAGE SQL;

CREATE TABLE DOCUMENTS (
    ID VARCHAR(255) PRIMARY KEY,
    TIME DATE NOT NULL,
    TITLE TEXT NOT NULL,
    DOCUMENT TEXT NOT NULL,
    TYPE TEXT NOT NULL
);

CREATE TABLE POSTS (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v1mc(),
    TITLE TEXT NOT NULL,
    POST TEXT NOT NULL
    
    -- Add more fields such as Post owner etc..
);

-- USER is a reserved keyword
CREATE TABLE VISITOR (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v1mc(),
    USERNAME VARCHAR(255) DEFAULT DEFAULT_NAME(),
    PW_HASH VARCHAR(255) 
);

-- We have to discuss how to implement Comments / Likes later.


-- Får implementera någon riktig grej sen som dynamiskt skapar användare eller nått
CREATE USER SCRAPERS WITH PASSWORD '123';

REVOKE ALL ON TABLE DOCUMENTS FROM SCRAPERS;
REVOKE ALL ON TABLE POSTS FROM SCRAPERS;
REVOKE ALL ON TABLE VISITOR FROM SCRAPERS;

GRANT INSERT ON TABLE DOCUMENTS TO SCRAPERS;


CREATE USER DELTA WITH PASSWORD '012';

REVOKE ALL ON TABLE DOCUMENTS FROM DELTA;
REVOKE ALL ON TABLE POSTS FROM SCRAPERS;
REVOKE ALL ON TABLE VISITOR FROM SCRAPERS;

GRANT SELECT ON TABLE DOCUMENTS TO DELTA;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE POSTS TO DELTA;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE VISITOR TO DELTA;

